        %include "freebsd/errno.asm"
        ;; %include "freebsd/file.asm"
        %include "freebsd/mman.asm"
        %include "freebsd/network.asm"
        %include "freebsd/signal.asm"
        %include "freebsd/socketcall.asm"