#!/usr/bin/python

import argparse, tempfile, sys, subprocess, os, readline, pwn

default_context = ['linux', 'i386']

parser = argparse.ArgumentParser()
parser.add_argument('hex', metavar='hex', nargs='?', help='Hex-string to disasemble. If none are supplied, then it uses stdin in non-hex mode.')
parser.add_argument('-c', '--context',
               metavar = '<opt>',
               choices = pwn.concat_all(pwn.possible_contexts.values()),
               action = 'append',
               help = 'The environment the shellcode will run in (default: %s), choose from %s' % \
               (' '.join(default_context),
                '; '.join('%s: %s' % (k, ', '.join(v for v in vs)) for k, vs in pwn.possible_contexts.items())),
               )
args = parser.parse_args()

pwn.context(*default_context) # 'reset' to defaults
if args.context:
    pwn.context(*args.context) # overwrite one or more options

if args.hex != None:
    print pwn.disasm(args.hex.decode("hex"))
else:
    print pwn.disasm(args.hex.decode("hex"))
    print pwn.disasm(sys.stdin.read())
