#!/usr/bin/python

import argparse, sys, readline, pwn, re

default_context = ['linux', 'i386']

parser = argparse.ArgumentParser()
parser.add_argument('hex', metavar='hex', nargs='*', help='Hex-string to disasemble. If none are supplied, then it uses stdin in non-hex mode.')
parser.add_argument('-c', '--context',
               metavar = '<opt>',
               choices = pwn.concat_all(pwn.possible_contexts.values()),
               action = 'append',
               help = 'The environment the shellcode will run in (default: %s), choose from %s' % \
               (' '.join(default_context),
                '; '.join('%s: %s' % (k, ', '.join(v for v in vs)) for k, vs in pwn.possible_contexts.items())),
               )
args = parser.parse_args()

pwn.context(*default_context) # 'reset' to defaults
if args.context:
    pwn.context(*args.context) # overwrite one or more options

if len(args.hex) > 0:
    dat = ''.join(args.hex)
    dat = re.sub(r'\s*', '', dat)
    if re.match('[^a-fA-F0-9]', dat):
        print "This is not a hex string"
        exit(-1)
    dat = dat.decode('hex')
else:
    dat = sys.stdin.read()

print pwn.disasm(dat)
