#!/usr/bin/env python
import pwn, sys

if __name__ == "__main__":
    if len(sys.argv) <> 2:
        print 'usage: %s <file>' % sys.argv[0]

    elf = pwn.ELF(sys.argv[1])
    print '\n'.join(k for k, _ in sorted(elf.plt.items(), key = lambda (_,x):x))
