#!/usr/bin/env python

import pwn, sys, hashlib

if not 2 <= len(sys.argv) <= 3:
    pwn.trace('Usage: ' + sys.argv[0] + ' host [filename]\n')
    pwn.die()

try:
    h = pwn.remote(sys.argv[1], port = 1337, timeout = None)
except Exception as e:
    pwn.die('Unable to connect to ' + sys.argv[1] + ':1337', e)

try:
    f = open(sys.argv[2], 'r') if len(sys.argv) == 3 else sys.stdin
except Exception as e:
    pwn.die('Unable to open file ' + sys.argv[2], e)

m = hashlib.md5()

while not f.closed:
    d = f.read(4095 * (len(sys.argv) == 3) + 1) # send as fast as the user can type
    if not d:
        break
    m.update(d)
    h.send(d)

pwn.trace(' [+] The MD5 hex-digest was: ' + m.hexdigest() + '\n')
