#!/bin/bash

if [ $# -eq 1 ] ; then
    tee >(nc -v "$1" 1337) | md5sum
elif [ $# -eq 2 ] ; then
    if [ -e "$2" ] ; then
        nc -v "$1" 1337 < "$2"
        md5sum "$2"
    else
        echo "File does not exist: $2"
    fi
else
    echo "usage: $0 [filename] host"
fi
