        ;; From /usr/include/bits/socket.h
        ;; Socket types
        %define SOCK_STREAM                     1
        %define SOCK_DGRAM                      2
        %define SOCK_RAW                        3
        %define SOCK_RDM                        4
        %define SOCK_SEQPACKET                  5
        %define SOCK_DCCP                       6
        %define SOCK_PACKET                     10
        ;; Protocol/address families
        %define PF_UNSPEC                       0
        %define AF_UNSPEC                       0
        %define PF_LOCAL                        1
        %define AF_LOCAL                        1
        %define PF_UNIX                         1
        %define AF_UNIX                         1
        %define PF_FILE                         1
        %define AF_FILE                         1
        %define PF_INET                         2
        %define AF_INET                         2
        %define PF_AX25                         3
        %define AF_AX25                         3
        %define PF_IPX                          4
        %define AF_IPX                          4
        %define PF_APPLETALK                    5
        %define AF_APPLETALK                    5
        %define PF_NETROM                       6
        %define AF_NETROM                       6
        %define PF_BRIDGE                       7
        %define AF_BRIDGE                       7
        %define PF_ATMPVC                       8
        %define AF_ATMPVC                       8
        %define PF_X25                          9
        %define AF_X25                          9
        %define PF_INET6                        10
        %define AF_INET6                        10
        %define PF_ROSE                         11
        %define AF_ROSE                         11
        %define PF_DECnet                       12
        %define AF_DECnet                       12
        %define PF_NETBEUI                      13
        %define AF_NETBEUI                      13
        %define PF_SECURITY                     14
        %define AF_SECURITY                     14
        %define PF_KEY                          15
        %define AF_KEY                          15
        %define PF_NETLINK                      16
        %define AF_NETLINK                      16
        %define PF_ROUTE                        16
        %define AF_ROUTE                        16
        %define PF_PACKET                       17
        %define AF_PACKET                       17
        %define PF_ASH                          18
        %define AF_ASH                          18
        %define PF_ECONET                       19
        %define AF_ECONET                       19
        %define PF_ATMSVC                       20
        %define AF_ATMSVC                       20
        %define PF_RDS                          21
        %define AF_RDS                          21
        %define PF_SNA                          22
        %define AF_SNA                          22
        %define PF_IRDA                         23
        %define AF_IRDA                         23
        %define PF_PPPOX                        24
        %define AF_PPPOX                        24
        %define PF_WANPIPE                      25
        %define AF_WANPIPE                      25
        %define PF_LLC                          26
        %define AF_LLC                          26
        %define PF_CAN                          29
        %define AF_CAN                          29
        %define PF_TIPC                         30
        %define AF_TIPC                         30
        %define PF_BLUETOOTH                    31
        %define AF_BLUETOOTH                    31
        %define PF_IUCV                         32
        %define AF_IUCV                         32
        %define PF_RXRPC                        33
        %define AF_RXRPC                        33
        %define PF_ISDN                         34
        %define AF_ISDN                         34
        %define PF_PHONET                       35
        %define AF_PHONET                       35
        %define PF_IEEE802154                   36
        %define AF_IEEE802154                   36
        %define PF_MAX                          37
        %define AF_MAX                          37
        ;; Bit in the FLAGS argument to 'send', 'recv', et al.
        %define MSG_OOB                         0x01
        %define MSG_PEEK                        0x02
        %define MSG_DONTROUTE                   0x04
        %define MSG_TRYHARD                     0x04
        %define MSG_CTRUNC                      0x08
        %define MSG_PROXY                       0x10
        %define MSG_TRUNC                       0x20
        %define MSG_DONTWAIT                    0x40
        %define MSG_EOR                         0x80
        %define MSG_WAITALL                     0x100
        %define MSG_FIN                         0x200
        %define MSG_SYN                         0x400
        %define MSG_CONFIRM                     0x800
        %define MSG_RST                         0x1000
        %define MSG_ERRQUEUE                    0x2000
        %define MSG_NOSIGNAL                    0x4000
        %define MSG_MORE                        0x8000
        %define MSG_CMSG_CLOEXEC                0x40000000

        ;; From /usr/include/netinet/in.h
        ;; IP protocols
        %define IPPROTO_IP                      0
        %define IPPROTO_HOPOPTS                 0
        %define IPPROTO_ICMP                    1
        %define IPPROTO_IGMP                    2
        %define IPPROTO_IPIP                    4
        %define IPPROTO_TCP                     6
        %define IPPROTO_EGP                     8
        %define IPPROTO_PUP                     12
        %define IPPROTO_UDP                     17
        %define IPPROTO_IDP                     22
        %define IPPROTO_TP                      29
        %define IPPROTO_DCCP                    33
        %define IPPROTO_IPV6                    41
        %define IPPROTO_ROUTING                 43
        %define IPPROTO_FRAGMENT                44
        %define IPPROTO_RSVP                    46
        %define IPPROTO_GRE                     47
        %define IPPROTO_ESP                     50
        %define IPPROTO_AH                      51
        %define IPPROTO_ICMPV6                  58
        %define IPPROTO_NONE                    59
        %define IPPROTO_DSTOPTS                 60
        %define IPPROTO_MTP                     92
        %define IPPROTO_ENCAP                   98
        %define IPPROTO_PIM                     103
        %define IPPROTO_COMP                    108
        %define IPPROTO_SCTP                    132
        %define IPPROTO_UDPLITE                 136
        %define IPPROTO_RAW                     255
        ;; Standard ports
        %define IPPORT_ECHO                     7
        %define IPPORT_DISCARD                  9
        %define IPPORT_SYSTAT                   11
        %define IPPORT_DAYTIME                  13
        %define IPPORT_NETSTAT                  15
        %define IPPORT_FTP                      21
        %define IPPORT_TELNET                   23
        %define IPPORT_SMTP                     25
        %define IPPORT_TIMESERVER               37
        %define IPPORT_NAMESERVER               42
        %define IPPORT_WHOIS                    43
        %define IPPORT_MTP                      57
        %define IPPORT_TFTP                     69
        %define IPPORT_RJE                      77
        %define IPPORT_FINGER                   79
        %define IPPORT_TTYLINK                  87
        %define IPPORT_SUPDUP                   95
        %define IPPORT_EXECSERVER               512
        %define IPPORT_LOGINSERVER              513
        %define IPPORT_CMDSERVER                514
        %define IPPORT_EFSSERVER                520
        %define IPPORT_BIFFUDP                  512
        %define IPPORT_WHOSERVER                513
        %define IPPORT_ROUTESERVER              520
        %define IPPORT_RESERVED                 1024
        %define IPPORT_USERRESERVED             5000
        ;; Special IP addresses
        %define INADDR_ANY                      0x00000000 ; 0.0.0.0
        %define INADDR_BROADCAST                0xffffffff ; 255.255.255.255
        %define INADDR_NONE                     0xffffffff ; 255.255.255.255
        %define INADDR_LOOPBACK                 0x7f000001 ; 127.0.0.1
        ;; Multicast addresses
        %define INADDR_UNSPEC_GROUP             0xe0000000 ; 224.0.0.0
        %define INADDR_ALLHOSTS_GROUP           0xe0000001 ; 224.0.0.1
        %define INADDR_ALLRTRS_GROUP            0xe0000002 ; 224.0.0.2
        %define INADDR_MAX_LOCAL_GROUP          0xe00000ff ; 224.0.0.255

        ;; From /usr/include/asm-generic/socket.h
        %define SOL_SOCKET                      1
        %define SO_DEBUG                        1
        %define SO_REUSEADDR                    2
        %define SO_TYPE                         3
        %define SO_ERROR                        4
        %define SO_DONTROUTE                    5
        %define SO_BROADCAST                    6
        %define SO_SNDBUF                       7
        %define SO_RCVBUF                       8
        %define SO_SNDBUFFORCE                  32
        %define SO_RCVBUFFORCE                  33
        %define SO_KEEPALIVE                    9
        %define SO_OOBINLINE                    10
        %define SO_NO_CHECK                     11
        %define SO_PRIORITY                     12
        %define SO_LINGER                       13
        %define SO_BSDCOMPAT                    14