        ;; Socket calls in /usr/include/linux/net.h
        %define SYS_socketcall_socket           1
        %define SYS_socketcall_bind             2
        %define SYS_socketcall_connect          3
        %define SYS_socketcall_listen           4
        %define SYS_socketcall_accept           5
        %define SYS_socketcall_getsockname      6
        %define SYS_socketcall_getpeername      7
        %define SYS_socketcall_socketpair       8
        %define SYS_socketcall_send             9
        %define SYS_socketcall_recv             10
        %define SYS_socketcall_sendto           11
        %define SYS_socketcall_recvfrom         12
        %define SYS_socketcall_shutdown         13
        %define SYS_socketcall_setsockopt       14
        %define SYS_socketcall_getsockopt       15
        %define SYS_socketcall_sendmsg          16
        %define SYS_socketcall_recvmsg          17
        %define SYS_socketcall_accept4          18