#!/usr/bin/env python
import os,sys
from methods import *
class packstar:
    def __init__(self):
        self.__method = None
        self.__data = None
        

    def setMethod(method):
        self.__method = method
    def setData(data):
        self.__data = data
    def pack():
        if(self.__data == None):
            print "No data was supplied to the packer"
            sys.exit(-1)
        if( self.__method == None):
            print "No packingmethod was selected when trying to pack"
            sys.exit(-1)
        self.__method.pack(self.__data)
        self.__method.test()
        return self.__method.getPackage()

def help():
    print "This is a help message"
    sys.exit(0)

def listMethods(methods):
    for method in methods.values():
        try:
            print method.description
        except AttributeError:
            print method.name
    sys.exit(0)
    
if __name__ == "__main__":
    try:
        _args = sys.argv[1:]
    except:
        help()
    methods = os.listdir("methods")
    methods.remove('__init__.py')
    methods = filter(lambda x: x.endswith('.py'),methods)
    methods = map( lambda x: x[:-3],methods)
    tmpmethods = {}
    for method in methods:
        __import__('methods.'+method,fromlist = ['Naive'])
        print method
        tmpmethods[method] = methods.Naive()
    methods = tmpmethods
    pack = packstar()
    i = 0
    while i < len(_args):
        arg  = _args[i]
        if arg in ['--list','-l']:
            listMethods(methods)
        elif arg in ['--help']:
            help()
        elif arg in ['--method','-m']:
            i += 1
            try:
                if _args[i] in methods:
                    pack.setMethod(_args[i])
                else:
                    print "The method you have selected is not valid"
                    print "Please select one on the following list"
                    listMethods(methods)
            except IndexError:
                raise Exception("Need more arguments")
                sys.exit(-1)
        elif arg in ['--data','-d']:
            i+= 1
            try:
                pack.setData(_args[i])
            except IndexError:
                raise Exception("Data not supplied")
                sys.exit(-1)
        else:
            print arg+ " isnt a valid argument"
            sys.exit(-1)
        i += 1
