from pwnlib.context import context
from pwnlib.util.packing import unpack


class linux_dirent:
    """
    struct linux_dirent
    {
      unsigned long d_ino;
      unsigned long d_off;
      unsigned short d_reclen;
      char d_name[];
    };

    enum
    {
        DT_UNKNOWN = 0,
        DT_FIFO = 1,
        DT_CHR = 2,
        DT_DIR = 4,
        DT_BLK = 6,
        DT_REG = 8,
        DT_LNK = 10,
        DT_SOCK = 12,
        DT_WHT = 14
    };
    """

    def __init__(self, buf: bytes, is_dirent64: bool):
        size_t = 8 if is_dirent64 else int(context.bits / 8)

        self.d_ino = unpack(buf[0:size_t])
        self.d_off = unpack(buf[size_t : 2 * size_t])
        self.d_reclen = unpack(buf[2 * size_t : 2 * size_t + 2], 16)

        if is_dirent64:
            self.d_type = unpack(buf[2 * size_t + 2 : 2 * size_t + 3], 8)
            self.d_name = (
                buf[2 * size_t + 3 : self.d_reclen - 1].rstrip(b'\x00').decode('utf-8')
            )
        else:
            self.d_name = (
                buf[2 * size_t + 2 : self.d_reclen - 1].rstrip(b'\x00').decode('utf-8')
            )
            self.d_type = unpack(buf[self.d_reclen - 1 : self.d_reclen], 8)

        if self.d_type == 0:
            self.d_type = 'unknown'
        elif self.d_type == 1:
            self.d_type = 'name pipe'
        elif self.d_type == 2:
            self.d_type = 'char dev'
        elif self.d_type == 4:
            self.d_type = 'directory'
        elif self.d_type == 6:
            self.d_type = 'block dev'
        elif self.d_type == 8:
            self.d_type = 'regular'
        elif self.d_type == 10:
            self.d_type = 'symlink'
        elif self.d_type == 12:
            self.d_type = 'socket'

    def __str__(self):
        return self.d_name

    def __repr__(self):
        return f'{self.d_type:<20} {self.d_name}'


def dirents(buf: bytes, is_dirent64: bool = False) -> list[linux_dirent]:
    """dirents(buf: bytes, is_dirent64: bool=False) -> list[linux_dirent]:

    Extracts data from a buffer emitted by getdents or getdents64

    Arguments:
        buf(bytes): Byte array
        is_dirent64(bool): Is buf generated by getdents64

    Returns:
        A list of file names

    Example:
        >>> with context.local(bits = 64):
        ...     buf = b'":,\x00\x00\x00\x00\x00\x8d4\x8d\x82\x8c0\xd5\x14 \x00wp.pdf\x00\x00\x00\x00\x00\x00\x00\x08\x16\x0b.\x00\x00\x00\x00\x00xjc\x1c\xc1 \xfc\x1a \x00a.out\x00\x00\x00\x00\x00\x00\x00\x00\x08\r\x00,\x00\x00\x00\x00\x00H\x02\xeeE\x1f4~0\x18\x00.\x00\x00\x00\x00\x04\x02\x00,\x00\x00\x00\x00\x00Qy\xc3\xfb\x97\xa3r=\x18\x00..\x00\x00\x00\x04\xae\x82,\x00\x00\x00\x00\x00\xc4\xdc\xa2\xa3\xf7\xbe<Z\x18\x00test\x00\x08\xb2,4\x00\x00\x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\x7f \x00flag-market\x00\x00\x04'
        ...     dirents(buf, False)
        ...
        [regular              wp.pdf, regular              a.out, directory            ., directory            .., regular              test, directory            flag-market]

    """

    bpos = 0
    buf_len = len(buf)
    entries = []

    while bpos < buf_len:
        dirent = linux_dirent(buf[bpos:], is_dirent64)
        bpos += dirent.d_reclen
        entries.append(dirent)
    return entries
