from os.path import split
from pwnlib.context import context
from pwnlib.util.packing import unpack
from pwnlib.util.fiddling import unhex


class linux_dirent:
    """
    struct linux_dirent
    {
      unsigned long d_ino;
      unsigned long d_off;
      unsigned short d_reclen;
      char d_name[];
    };

    struct linux_dirent64 {
        u64		d_ino;
        s64		d_off;
        unsigned short	d_reclen;
        unsigned char	d_type;
        char		d_name[];
    };

    enum
    {
        DT_UNKNOWN = 0,
        DT_FIFO = 1,
        DT_CHR = 2,
        DT_DIR = 4,
        DT_BLK = 6,
        DT_REG = 8,
        DT_LNK = 10,
        DT_SOCK = 12,
        DT_WHT = 14
    };
    """

    def __init__(self, buf: bytes, is_dirent64: bool):
        size_t = 8 if is_dirent64 else int(context.bits / 8)

        self.d_ino = unpack(buf[0:size_t])
        self.d_off = unpack(buf[size_t : 2 * size_t])
        self.d_reclen = unpack(buf[2 * size_t : 2 * size_t + 2], 16)

        if is_dirent64:
            self.d_type = unpack(buf[2 * size_t + 2 : 2 * size_t + 3], 8)
            try:
                self.d_name = buf[2 * size_t + 3 : self.d_reclen - 1].split(b'\x00', 1)[0].decode('utf-8')
            except UnicodeDecodeError:
                print("Decode Error: ", buf[2 * size_t + 3: self.d_reclen - 1])
                exit(1)

        else:
            self.d_type = unpack(buf[self.d_reclen - 1 : self.d_reclen], 8)
            try:
                self.d_name = buf[2 * size_t + 2 : self.d_reclen - 1].split(b'\x00', 1)[0].decode('utf-8')
            except UnicodeDecodeError:
                print("Decode Error: ", buf[2 * size_t + 2: self.d_reclen - 1])
                exit(1)

        if self.d_type == 0:
            self.d_type = 'unknown'
        elif self.d_type == 1:
            self.d_type = 'name pipe'
        elif self.d_type == 2:
            self.d_type = 'char dev'
        elif self.d_type == 4:
            self.d_type = 'directory'
        elif self.d_type == 6:
            self.d_type = 'block dev'
        elif self.d_type == 8:
            self.d_type = 'regular'
        elif self.d_type == 10:
            self.d_type = 'symlink'
        elif self.d_type == 12:
            self.d_type = 'socket'

    def __str__(self):
        return self.d_name

    def __repr__(self):
        return f'{self.d_type:<20} {self.d_name}'


def dirents(buf: bytes, is_dirent64: bool = False) -> list[linux_dirent]:
    """dirents(buf: bytes, is_dirent64: bool=False) -> list[linux_dirent]:

    Extracts data from a buffer emitted by getdents or getdents64

    Arguments:
        buf(bytes): Byte array
        is_dirent64(bool): Is buf generated by getdents64

    Returns:
        A list of file names

    Example:
        >>> with context.local(bits = 64):
        >>> buf = unhex('223a2c0000000000786a631cc120fc1a2000746573742e6300e57464040000080d002c00000000004802ee451f347e3018002e000000000402002c0000000000ffffffffffffff7f18002e2e00000004')
        >>> dirents(buf, False)
        [regular              test.c, directory            ., directory            ..]

        >>> buf = unhex('223a2c0000000000786a631cc120fc1a200008746573742e63007464040000000d002c00000000004802ee451f347e301800042e0000000002002c0000000000ffffffffffffff7f1800042e2e000000')
        >>> dirents(buf, True)
        [regular              test.c, directory            ., directory            ..]
    """

    bpos = 0
    buf_len = len(buf)
    entries = []

    while bpos < buf_len:
        dirent = linux_dirent(buf[bpos:], is_dirent64)
        bpos += dirent.d_reclen
        entries.append(dirent)
    return entries
