"""
Functions for computing various hashes of files and strings.
"""
import hashlib
from typing import TYPE_CHECKING

for _algo in hashlib.algorithms_guaranteed:
    def _closure():
        hash = hashlib.__dict__[_algo]
        def file(p):
            h = hash()
            fd = open(p, 'rb')
            while True:
                s = fd.read(4096)
                if not s:
                    break
                h.update(s)
            fd.close()
            return h
        def sum(s):
            return hash(s)
        filef = lambda x: file(x).digest()
        filef.__doc__ = 'Calculates the %s sum of a file' % _algo
        sumf = lambda x: sum(x).digest()
        sumf.__doc__ = 'Calculates the %s sum of a string' % _algo
        fileh = lambda x: file(x).hexdigest()
        fileh.__doc__ = 'Calculates the %s sum of a file; returns hex-encoded' % _algo
        sumh = lambda x: sum(x).hexdigest()
        sumh.__doc__ = 'Calculates the %s sum of a string; returns hex-encoded' % _algo
        return filef, sumf, fileh, sumh
    (globals()[_algo + 'file'],
     globals()[_algo + 'sum'],
     globals()[_algo + 'filehex'],
     globals()[_algo + 'sumhex']) = _closure()

if TYPE_CHECKING:
    def sha256file(data: bytes | bytearray) -> bytes: ...
    def sha256sum(data: bytes | bytearray) -> bytes: ...
    def sha256filehex(data: bytes | bytearray) -> str: ...
    def sha256sumhex(data: bytes | bytearray) -> str: ...
    def md5file(data: bytes | bytearray) -> bytes: ...
    def md5sum(data: bytes | bytearray) -> bytes: ...
    def md5filehex(data: bytes | bytearray) -> str: ...
    def md5sumhex(data: bytes | bytearray) -> str: ...
    def sha3_384file(data: bytes | bytearray) -> bytes: ...
    def sha3_384sum(data: bytes | bytearray) -> bytes: ...
    def sha3_384filehex(data: bytes | bytearray) -> str: ...
    def sha3_384sumhex(data: bytes | bytearray) -> str: ...
    def sha512file(data: bytes | bytearray) -> bytes: ...
    def sha512sum(data: bytes | bytearray) -> bytes: ...
    def sha512filehex(data: bytes | bytearray) -> str: ...
    def sha512sumhex(data: bytes | bytearray) -> str: ...
    def shake_128file(data: bytes | bytearray) -> bytes: ...
    def shake_128sum(data: bytes | bytearray) -> bytes: ...
    def shake_128filehex(data: bytes | bytearray) -> str: ...
    def shake_128sumhex(data: bytes | bytearray) -> str: ...
    def sha384file(data: bytes | bytearray) -> bytes: ...
    def sha384sum(data: bytes | bytearray) -> bytes: ...
    def sha384filehex(data: bytes | bytearray) -> str: ...
    def sha384sumhex(data: bytes | bytearray) -> str: ...
    def sha3_224file(data: bytes | bytearray) -> bytes: ...
    def sha3_224sum(data: bytes | bytearray) -> bytes: ...
    def sha3_224filehex(data: bytes | bytearray) -> str: ...
    def sha3_224sumhex(data: bytes | bytearray) -> str: ...
    def sha3_512file(data: bytes | bytearray) -> bytes: ...
    def sha3_512sum(data: bytes | bytearray) -> bytes: ...
    def sha3_512filehex(data: bytes | bytearray) -> str: ...
    def sha3_512sumhex(data: bytes | bytearray) -> str: ...
    def shake_256file(data: bytes | bytearray) -> bytes: ...
    def shake_256sum(data: bytes | bytearray) -> bytes: ...
    def shake_256filehex(data: bytes | bytearray) -> str: ...
    def shake_256sumhex(data: bytes | bytearray) -> str: ...
    def sha3_256file(data: bytes | bytearray) -> bytes: ...
    def sha3_256sum(data: bytes | bytearray) -> bytes: ...
    def sha3_256filehex(data: bytes | bytearray) -> str: ...
    def sha3_256sumhex(data: bytes | bytearray) -> str: ...
    def sha1file(data: bytes | bytearray) -> bytes: ...
    def sha1sum(data: bytes | bytearray) -> bytes: ...
    def sha1filehex(data: bytes | bytearray) -> str: ...
    def sha1sumhex(data: bytes | bytearray) -> str: ...
    def blake2bfile(data: bytes | bytearray) -> bytes: ...
    def blake2bsum(data: bytes | bytearray) -> bytes: ...
    def blake2bfilehex(data: bytes | bytearray) -> str: ...
    def blake2bsumhex(data: bytes | bytearray) -> str: ...
    def sha224file(data: bytes | bytearray) -> bytes: ...
    def sha224sum(data: bytes | bytearray) -> bytes: ...
    def sha224filehex(data: bytes | bytearray) -> str: ...
    def sha224sumhex(data: bytes | bytearray) -> str: ...
    def blake2sfile(data: bytes | bytearray) -> bytes: ...
    def blake2ssum(data: bytes | bytearray) -> bytes: ...
    def blake2sfilehex(data: bytes | bytearray) -> str: ...
    def blake2ssumhex(data: bytes | bytearray) -> str: ...
