#!/usr/bin/env python
from binascii import unhexlify
import sys

try:
    if len(sys.argv) == 1:
        s = sys.stdin.read()
        if s[-1] == '\n':
            s = s[:-1]
        print unhexlify(s)
    else:
        print unhexlify(' '.join(sys.argv[1:]))
except TypeError, e:
    sys.stderr.write(str(e) + '\n')
