#!/usr/bin/env python
from binascii import unhexlify
import sys

try:
    if len(sys.argv) == 1:
        s = sys.stdin.read()
        if s[-1] == '\n':
            s = s[:-1]
        sys.stdout.write(unhexlify(s))
    else:
        sys.stdout.write(unhexlify(' '.join(sys.argv[1:])))
except TypeError, e:
    sys.stderr.write(str(e) + '\n')
