#!/usr/bin/env bash

reset

# We have to explicitly start the ssh service
sudo service ssh start

# Enable the IPv6 interface
echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6

# Run the tests from the repo
cd ~

ORIG_TARGET="$TARGET"

if [ -n "$TARGET" ]; then
	TARGET=$(find ~/pwntools/docs/source -iname "$TARGET")

	if [ -z "$TARGET" ]; then
		echo "Could not find target $ORIG_TARGET"
		exit 1
	fi

	echo "DOCTEST TARGET is $TARGET"
fi

export PWNLIB_NOTERM=1 
coverage-2.7 run -m sphinx -b doctest $HOME/pwntools/docs/source $HOME/pwntools/docs/build/doctest $TARGET

