#!/usr/bin/env bash

# We have to explicitly start the ssh service
sudo service ssh start

# Enable the IPv6 interface
echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6

# Run the tests from the repo
cd ~

if [ -n "$TARGET" ]; then
	echo "DOCTEST TARGET is $TARGET"
fi

PWNLIB_NOTERM=1 coverage3 run -m sphinx -b doctest $HOME/pwntools/docs/source $HOME/pwntools/docs/build/doctest $TARGET

