name: Android Tests

on: [push, pull_request]

jobs:
  android-test:
    strategy:
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends -o Acquire::Retries=3 \
          gdb gdbserver socat \
          qemu-user-static \
          binutils-aarch64-linux-gnu \
          binutils-arm-linux-gnueabihf \
          libc6-dbg

    - name: Cache for avd
      uses: actions/cache@v4
      id: cache-avd
      with:
        path: |
          ~/.android
          /usr/local/lib/android/sdk/emulator
          /usr/local/lib/android/sdk/platform-tools
          /usr/local/lib/android/sdk/system-images
        key: ${{ matrix.os }}-cache-avd-${{ hashFiles('travis/setup_avd*.sh') }}
        restore-keys: |
          ${{ matrix.os }}-cache-avd-

    - name: Install Android AVD
      run: |
        sudo usermod -aG kvm $USER
        source travis/setup_avd_fast.sh
        sed -i 's/skip_android = True/skip_android = False/' docs/source/conf.py
        set | grep ^PATH >.android.env

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        python setup.py egg_info
        pip install --upgrade --editable .

    - name: Sanity checks
      run:  PWNLIB_NOTERM=1 python -c 'from pwn import *; print(pwnlib.term.term_mode)'

    - name: Install documentation dependencies
      run:  pip install -r docs/requirements.txt

    - name: Coverage Doctests (Android Only)
      run: |
        source .android.env
        PWNLIB_NOTERM=1 coverage run -m sphinx -b doctest docs/source docs/build/doctest docs/source/adb.rst
